server:
    port: 8080

spring:
    profiles: dev
    data:
        mongodb:
            host: localhost
            port: 27017
            databaseName: rpg-portfolio
    

    mail:
        baseUrl: http://localhost:8080

    thymeleaf:
        mode: XHTML
        cache: false
        viewNames: error

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host: localhost
        port: 2003



# You can add as many as folders to watch
# You just need to add a dash + the directory to watch
hotReload:
    enabled: true
    package:
      project: fr.hervedarritchon.rpgportfolio
      domain: fr.hervedarritchon.rpgportfolio.domain
      restdto: fr.hervedarritchon.rpgportfolio.web.rest.dto
    watchdir:
      - target/classes
